from game_history import GameHistory
from tests.helpers import convert_board_to_string, convert_string_to_board

def test_game_history():
    turn_0 = """\
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""
    turn_1 = """\
...............
...............
...............
...............
...............
...............
...............
.......●.......
...............
...............
...............
...............
...............
...............
...............
""" 
    turn_2 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○......
...............
...............
...............
...............
...............
...............
...............
""" 
    turn_3 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○......
...............
...............
.......●.......
...............
...............
...............
...............
""" 
    turn_4 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○○.....
...............
...............
.......●.......
...............
...............
...............
...............
""" 
    turn_5 = """\
...............
...............
...............
...............
...............
...............
...............
.......●..●....
...............
...............
.......●.......
...............
...............
...............
...............
""" 
    game_history = GameHistory(15)
    game_history.record_move(7, 7)
    assert game_history.get_first_turn().board == convert_string_to_board(turn_0)
    assert game_history.get_last_turn().board == convert_string_to_board(turn_1)
    game_history.record_move(8, 7)
    assert game_history.get_last_turn().board == convert_string_to_board(turn_2)
    game_history.record_move(7, 10)
    assert game_history.get_last_turn().board == convert_string_to_board(turn_3)
    game_history.record_move(9, 7)
    assert game_history.get_last_turn().board == convert_string_to_board(turn_4)
    game_history.record_move(10, 7)
    assert game_history.get_last_turn().board == convert_string_to_board(turn_5)
    assert game_history.get_nth_turn(1).board == convert_string_to_board(turn_1)
    assert game_history.get_nth_turn(2).board == convert_string_to_board(turn_2)
    assert game_history.get_nth_turn(3).board == convert_string_to_board(turn_3)
    assert game_history.get_nth_turn(4).board == convert_string_to_board(turn_4)
    assert game_history.get_nth_turn(5).board == convert_string_to_board(turn_5)
