from game_history import GameHistory
from gomoku import Gomoku
from tests.helpers import convert_string_to_board

def test_full_game_history():
    turn_0 = """\
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""
    turn_1 = """\
...............
...............
...............
...............
...............
...............
...............
.......●.......
...............
...............
...............
...............
...............
...............
...............
""" 
    turn_2 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○......
...............
...............
...............
...............
...............
...............
...............
""" 
    turn_3 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○......
...............
...............
.......●.......
...............
...............
...............
...............
""" 
    turn_4 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○○.....
...............
...............
.......●.......
...............
...............
...............
...............
""" 
    turn_5 = """\
...............
...............
...............
...............
...............
...............
...............
.......●..●....
...............
...............
.......●.......
...............
...............
...............
...............
""" 
    turn_6 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○.●....
...............
...............
.......●.......
...............
...............
...............
...............
""" 
    turn_7 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○.●....
...............
.......●.......
.......●.......
...............
...............
...............
...............
"""
    turn_8 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○.●....
...............
.......●.......
.......●.......
.......○.......
...............
...............
...............
"""
    turn_9 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○.●....
.......●.......
.......●.......
.......●.......
.......○.......
...............
...............
...............
"""
    turn_10 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○.●....
.......●.......
.......●.......
.......●.......
.......○.......
........○......
...............
...............
"""
    turn_11 = """\
...............
...............
...............
...............
...............
...............
.......●.......
.......●○.●....
.......●.......
.......●.......
.......●.......
.......○.......
........○......
...............
...............
"""

    game_history = GameHistory(15)
    result = game_history.record_move(7, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_first_turn().board == convert_string_to_board(turn_0)
    assert game_history.get_last_turn().board == convert_string_to_board(turn_1)
    result = game_history.record_move(8, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_2)
    result = game_history.record_move(7, 10)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_3)
    result = game_history.record_move(9, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_4)
    result = game_history.record_move(10, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_5)
    result = game_history.record_move(8, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_6)
    result = game_history.record_move(7, 9)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_7)
    result = game_history.record_move(7, 11)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_8)
    result = game_history.record_move(7, 8)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_9)
    result = game_history.record_move(8, 12)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_10)
    result = game_history.record_move(7, 6)
    assert result["status"] == Gomoku.WIN
    assert game_history.get_last_turn().board == convert_string_to_board(turn_11)

    assert game_history.get_nth_turn(0).board == convert_string_to_board(turn_0)
    assert game_history.get_nth_turn(1).board == convert_string_to_board(turn_1)
    assert game_history.get_nth_turn(2).board == convert_string_to_board(turn_2)
    assert game_history.get_nth_turn(3).board == convert_string_to_board(turn_3)
    assert game_history.get_nth_turn(4).board == convert_string_to_board(turn_4)
    assert game_history.get_nth_turn(5).board == convert_string_to_board(turn_5)
    assert game_history.get_nth_turn(6).board == convert_string_to_board(turn_6)
    assert game_history.get_nth_turn(7).board == convert_string_to_board(turn_7)
    assert game_history.get_nth_turn(8).board == convert_string_to_board(turn_8)
    assert game_history.get_nth_turn(9).board == convert_string_to_board(turn_9)
    assert game_history.get_nth_turn(10).board == convert_string_to_board(turn_10)
    assert game_history.get_nth_turn(11).board == convert_string_to_board(turn_11)

def test_illegal_first_move():
    """Test when the first move is nt at the the center of the board.
    """
    game_history = GameHistory(15)
    result = game_history.record_move(7, 6)
    assert result["status"] == Gomoku.INVALID_MOVE

def test_illegal_second_move():
    """Test when the second move is on the same square as the first move.
    """
    game_history = GameHistory(15)
    result = game_history.record_move(7, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    result = game_history.record_move(7, 7)
    assert result["status"] == Gomoku.INVALID_MOVE

def test_illegal_third_move():
    """Test when the third move is in the central region.
    """
    game_history = GameHistory(15)
    result = game_history.record_move(7, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    result = game_history.record_move(7, 8)
    assert result["status"] == Gomoku.VALID_MOVE
    result = game_history.record_move(7, 9)
    assert result["status"] == Gomoku.INVALID_MOVE
