from typing import Optional
from gomoku import Gomoku

def convert_go_ban(board: str) -> list[list[int]]:
    # convert the go ban to a 2D array
    # '.' -> 0
    # '●' -> 1
    # '○' -> -1
    tempo = [[int(cell == '●') - int(cell == '○') for cell in line] for line in board.splitlines()]
    return [list(i) for i in zip(*tempo)]


def assert_code_and_message(board: str, x: int, y: int, black_takes: int, white_takes: int, turn_number: int, expected_status: int, expected_message: Optional[str]):
    gomoku = Gomoku(15)
    gomoku.set(convert_go_ban(board), black_takes, white_takes, turn_number)
    result = gomoku.manage_move(x, y)
    assert result['status'] == expected_status
    assert result['message'] == expected_message
    assert len(result['removed_stones']) == 0

def test_legal_first_move():
    str = """\
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""
    assert_code_and_message(str, 7, 7, 0, 0, 0, Gomoku.VALID_MOVE, None)

def test_illegal_first_move():
    str = """\
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""
    assert_code_and_message(str, 0, 0, 0, 0, 0, Gomoku.INVALID_MOVE, "First move must be in the center")

def test_illegal_third_move_north():
    str = """\
...............
...............
...............
...............
...............
...............
.......●.......
.......○.......
...............
...............
...............
...............
...............
...............
...............
"""
    assert_code_and_message(str, 7, 5, 0, 0,2, Gomoku.INVALID_MOVE, "Third move must be out of central 5×5 square")

def test_illegal_third_move_south():
    str = """\
...............
...............
...............
...............
...............
...............
.......●.......
.......○.......
...............
...............
...............
...............
...............
...............
...............
"""
    assert_code_and_message(str, 7, 9, 0, 0, 2, Gomoku.INVALID_MOVE, "Third move must be out of central 5×5 square")
    
def test_illegal_third_move_west():
    str = """\
...............
...............
...............
...............
...............
...............
.......●.......
.......○.......
...............
...............
...............
...............
...............
...............
...............
"""
    assert_code_and_message(str, 5, 7, 0, 0, 2, Gomoku.INVALID_MOVE, "Third move must be out of central 5×5 square")

def test_illegal_third_move_east():
    str = """\
...............
...............
...............
...............
...............
...............
.......●.......
.......○.......
...............
...............
...............
...............
...............
...............
...............
"""
    assert_code_and_message(str, 9, 7, 0, 0, 2, Gomoku.INVALID_MOVE, "Third move must be out of central 5×5 square")

def test_legal_third_move():
    str = """\
...............
...............
...............
...............
...............
...............
.......●.......
.......○.......
...............
...............
...............
...............
...............
...............
...............
"""
    assert_code_and_message(str, 4, 4, 0, 0, 2, Gomoku.VALID_MOVE, None)

def test_move_out_of_go_ban():
    str = """\
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""
    assert_code_and_message(str, 16, 0, 0, 0, 0, Gomoku.INVALID_MOVE, "Move out of the go ban")

def test_move_on_occupied_cell():
    str = """\
..............○
...●..........○
...............
...............
...............
...............
...............
...............
...●...........
...............
...............
...............
...............
...............
...............
"""
    assert_code_and_message(str, 3, 1, 0, 0, 4, Gomoku.INVALID_MOVE, "Move on an already played cell")

def test_detect_horizontal_black_win_top_right_corner():
    str = """\
●.●●●..........
○..............
○..............
○..............
○..............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""
    assert_code_and_message(str, 1, 0, 0, 0, 8, Gomoku.WIN, "Player 1 wins (horizontal alignment)")

def test_detect_vertical_black_win_bottom_right_corner():
    str = """\
○○○○...........
...............
...............
...............
...............
...............
...............
...............
...............
...............
.●.............
.●.............
...............
.●.............
.●.............
"""
    assert_code_and_message(str, 1, 12, 0, 0, 8, Gomoku.WIN, "Player 1 wins (vertical alignment)")

def test_detect_diagonal_black_win_bottom_left_corner():
    str = """\
○○○○...........
...............
...............
...............
...............
...............
...............
...............
...............
...............
.........●.....
..........●....
...........●...
............●..
...............
"""
    assert_code_and_message(str, 13, 14, 0, 0, 8, Gomoku.WIN, "Player 1 wins (diagonal alignment)")

def test_detect_anti_diagonal_black_win_bottom_left_corner():
    str = """\
○○○○...........
...............
...............
...............
...............
...............
...............
...............
...............
...............
..............●
...............
............●..
...........●...
..........●....
"""
    assert_code_and_message(str, 13, 11, 0, 0, 8, Gomoku.WIN, "Player 1 wins (anti-diagonal alignment)")


def test_detect_horizontal_white_win_top_right_corner():
    str = """\
○.○○○..........
●..............
●..............
●..............
●●.............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""
    assert_code_and_message(str, 1, 0, 0, 0, 9, Gomoku.WIN, "Player -1 wins (horizontal alignment)")

def test_detect_vertical_white_win_bottom_right_corner():
    str = """\
●●●●...........
●..............
...............
...............
...............
...............
...............
...............
...............
...............
.○.............
.○.............
...............
.○.............
.○.............
"""
    assert_code_and_message(str, 1, 12, 0, 0, 9, Gomoku.WIN, "Player -1 wins (vertical alignment)")

def test_detect_diagonal_white_win_bottom_left_corner():
    str = """\
●●●●...........
●..............
...............
...............
...............
...............
...............
...............
...............
...............
.........○.....
..........○....
...........○...
............○..
...............
"""
    assert_code_and_message(str, 13, 14, 0, 0, 9, Gomoku.WIN, "Player -1 wins (diagonal alignment)")

def test_detect_anti_diagonal_white_win_bottom_left_corner():
    str = """\
●●●●...........
●..............
...............
...............
...............
...............
...............
...............
...............
...............
..............○
...............
............○..
...........○...
..........○....
"""
    assert_code_and_message(str, 13, 11, 0, 0, 9, Gomoku.WIN, "Player -1 wins (anti-diagonal alignment)")

def test_detect_black_takes_three_takes():
    str = """\
●..●●●●........
.○.○...........
..○○...........
●○○............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""
    gomoku = Gomoku(15)
    gomoku.set(convert_go_ban(str), 0, 0, 12)
    result = gomoku.manage_move(3, 3)
    assert result['status'] == Gomoku.VALID_MOVE
    assert result['message'] == None
    assert set(result['removed_stones']) == {(1, 1), (1, 3), (2, 2), (2, 3), (3, 1), (3, 2)}

def test_detect_black_takes_two_takes_and_wins():
    str = """\
●..............
...............
●..............
...............
●..............
...............
●..............
...............
●..............
...............
●..............
............○○●
...........○●..
...........○...
...........●..●
"""
    gomoku = Gomoku(15)
    gomoku.set(convert_go_ban(str), 3, 0, 20)
    result = gomoku.manage_move(11, 11)
    assert result['status'] == Gomoku.WIN
    assert result['message'] == "Player 1 wins (5 takes)"
    assert set(result['removed_stones']) == {(11, 12), (11, 13), (12, 11), (13, 11)}
