from pathlib import Path
from game_history import GameHistory
from gomoku import Gomoku
from tests.helpers import convert_string_to_board

def test_full_game_history() -> None:
    turn_0 = """\
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
"""
    turn_1 = """\
...............
...............
...............
...............
...............
...............
...............
.......●.......
...............
...............
...............
...............
...............
...............
...............
""" 
    turn_2 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○......
...............
...............
...............
...............
...............
...............
...............
""" 
    turn_3 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○......
...............
...............
.......●.......
...............
...............
...............
...............
""" 
    turn_4 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○○.....
...............
...............
.......●.......
...............
...............
...............
...............
""" 
    turn_5 = """\
...............
...............
...............
...............
...............
...............
...............
.......●..●....
...............
...............
.......●.......
...............
...............
...............
...............
""" 
    turn_6 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○.●....
...............
...............
.......●.......
...............
...............
...............
...............
""" 
    turn_7 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○.●....
...............
.......●.......
.......●.......
...............
...............
...............
...............
"""
    turn_8 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○.●....
...............
.......●.......
.......●.......
.......○.......
...............
...............
...............
"""
    turn_9 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○.●....
.......●.......
.......●.......
.......●.......
.......○.......
...............
...............
...............
"""
    turn_10 = """\
...............
...............
...............
...............
...............
...............
...............
.......●○.●....
.......●.......
.......●.......
.......●.......
.......○.......
........○......
...............
...............
"""
    turn_11 = """\
...............
...............
...............
...............
...............
...............
.......●.......
.......●○.●....
.......●.......
.......●.......
.......●.......
.......○.......
........○......
...............
...............
"""

    game_history = GameHistory(15)
    result = game_history.record_move(7, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_first_turn().board == convert_string_to_board(turn_0)
    assert game_history.get_last_turn().board == convert_string_to_board(turn_1)
    result = game_history.record_move(8, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_2)
    result = game_history.record_move(7, 10)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_3)
    result = game_history.record_move(9, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_4)
    result = game_history.record_move(10, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_5)
    result = game_history.record_move(8, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_6)
    result = game_history.record_move(7, 9)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_7)
    result = game_history.record_move(7, 11)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_8)
    result = game_history.record_move(7, 8)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_9)
    result = game_history.record_move(8, 12)
    assert result["status"] == Gomoku.VALID_MOVE
    assert game_history.get_last_turn().board == convert_string_to_board(turn_10)
    result = game_history.record_move(7, 6)
    assert result["status"] == Gomoku.WIN
    assert game_history.get_last_turn().board == convert_string_to_board(turn_11)

    assert game_history.get_nth_turn(0).board == convert_string_to_board(turn_0)
    assert game_history.get_nth_turn(0).black_takes == 0
    assert game_history.get_nth_turn(0).white_takes == 0
    assert game_history.get_nth_turn(1).board == convert_string_to_board(turn_1)
    assert game_history.get_nth_turn(1).black_takes == 0
    assert game_history.get_nth_turn(1).white_takes == 0
    assert game_history.get_nth_turn(2).board == convert_string_to_board(turn_2)
    assert game_history.get_nth_turn(2).black_takes == 0
    assert game_history.get_nth_turn(2).white_takes == 0
    assert game_history.get_nth_turn(3).board == convert_string_to_board(turn_3)
    assert game_history.get_nth_turn(3).black_takes == 0
    assert game_history.get_nth_turn(3).white_takes == 0
    assert game_history.get_nth_turn(4).board == convert_string_to_board(turn_4)
    assert game_history.get_nth_turn(4).black_takes == 0
    assert game_history.get_nth_turn(4).white_takes == 0
    assert game_history.get_nth_turn(5).board == convert_string_to_board(turn_5)
    assert game_history.get_nth_turn(5).black_takes == 1
    assert game_history.get_nth_turn(5).white_takes == 0
    assert game_history.get_nth_turn(6).board == convert_string_to_board(turn_6)
    assert game_history.get_nth_turn(6).black_takes == 1
    assert game_history.get_nth_turn(6).white_takes == 0
    assert game_history.get_nth_turn(7).board == convert_string_to_board(turn_7)
    assert game_history.get_nth_turn(7).black_takes == 1
    assert game_history.get_nth_turn(7).white_takes == 0
    assert game_history.get_nth_turn(8).board == convert_string_to_board(turn_8)
    assert game_history.get_nth_turn(8).black_takes == 1
    assert game_history.get_nth_turn(8).white_takes == 0
    assert game_history.get_nth_turn(9).board == convert_string_to_board(turn_9)
    assert game_history.get_nth_turn(9).black_takes == 1
    assert game_history.get_nth_turn(9).white_takes == 0
    assert game_history.get_nth_turn(10).board == convert_string_to_board(turn_10)
    assert game_history.get_nth_turn(10).black_takes == 1
    assert game_history.get_nth_turn(10).white_takes == 0
    assert game_history.get_nth_turn(11).board == convert_string_to_board(turn_11)
    assert game_history.get_nth_turn(11).black_takes == 1
    assert game_history.get_nth_turn(11).white_takes == 0

def test_illegal_first_move() -> None:
    """Test when the first move is nt at the the center of the board.
    """
    game_history = GameHistory(15)
    result = game_history.record_move(7, 6)
    assert result["status"] == Gomoku.INVALID_MOVE

def test_illegal_second_move() -> None:
    """Test when the second move is on the same square as the first move.
    """
    game_history = GameHistory(15)
    result = game_history.record_move(7, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    result = game_history.record_move(7, 7)
    assert result["status"] == Gomoku.INVALID_MOVE

def test_illegal_third_move() -> None:
    """Test when the third move is in the central region.
    """
    game_history = GameHistory(15)
    result = game_history.record_move(7, 7)
    assert result["status"] == Gomoku.VALID_MOVE
    result = game_history.record_move(7, 8)
    assert result["status"] == Gomoku.VALID_MOVE
    result = game_history.record_move(7, 9)
    assert result["status"] == Gomoku.INVALID_MOVE

def test_save_and_load_history(tmp_path: Path) -> None:
    """
    Tests saving the game history to a file and loading it back.
    """
    # 1. Create a GameHistory instance and record some moves
    history = GameHistory(19)
    history.record_move(9, 9)
    history.record_move(10, 10)
    history.record_move(8, 8)

    # 2. Save the history to a file
    file_path = tmp_path / "history.json"
    history.save_to_file(str(file_path))

    # 3. Load the history from the file
    loaded_history = GameHistory.load_from_file(str(file_path))

    # 4. Assert that the loaded history is identical to the original
    assert loaded_history.first_frame.size == history.first_frame.size
    assert loaded_history.history == history.history

    # Check the state of the last frame
    original_last_turn = history.get_last_turn()
    loaded_last_turn = loaded_history.get_last_turn()

    assert original_last_turn.board == loaded_last_turn.board
    assert original_last_turn.turn_number == loaded_last_turn.turn_number
    assert original_last_turn.black_takes == loaded_last_turn.black_takes
    assert original_last_turn.white_takes == loaded_last_turn.white_takes
